### ISSUE TITLE
WNDR3700 v1

### ISSUE THREAD

**Issue by edjka** [gwlim/openwrt-sfe-flowoffload#75]
Getting an error on September build, when trying to enter Firewall settings -
RPC call failed with error -32002: Access denied
at handleCallReply (http://192.168.1.1/luci-static/resources/rpc.js:8:12)
at promise callback*call (http://192.168.1.1/luci-static/resources/rpc.js:5:95)
at declare/

Any ideas to fix this?

**Comment by gwlim** [comment]
your javascript has been caching the old rpc call.
clear browser cache or use private mode
